- name: add sudoadmin group
  group: name={{item}} state=present
  with_items:
    - sudoadmin
    - sudoers

# add user and group stuff
- name: add {{user}} and home {{user_home_base}}/{{user}}
  action: user name={{user}} uid=2030 shell=/bin/bash groups=sudoadmin append=yes home={{user_home_base}}/{{user}}

# change owner and goup for user directory
- name: create home directory {{user_home_base}}/{{user}}
  action: file path={{user_home_base}}/{{user}} group={{user}} owner={{user}}

# first create home directory
- name: create ssh directory {{user_home_base}}/{{user}}
  action: file path={{user_home_base}}/{{user}}/.ssh state=directory owner={{user}} group={{user}}

- name: create htdocs directory
  file: path={{user_home_base}}/{{user}}/htdocs src=/data state=link

# we used synced folders in vagrant for dev.local - so we dont need to create the folder here on filesystem
#- name: create dev.local directory
#  action: file path={{user_home_base}}/{{user}}/htdocs/dev.local state=directory owner={{user}} group={{user}}

# copy all static files needed for a user to his homedir
- name: copy static user files
  copy: src=../files{{ item.path }} dest={{user_home_base}}/{{user}}{{ item.dest }} owner={{user}} group={{user}}
  with_items:
    - { path: '/.bashrc', dest: '/.bashrc', mode: 644 }
    - { path: '/.gitignore_global', dest: '/.gitignore_global', mode: 644 }
    - { path: '/.vimrc', dest: '/.vimrc', mode: 644 }
    - { path: '/ssh_config', dest: '/.ssh/ssh_config', mode: 600 }

- name: create dynamic user files from template
  template: src=../templates{{item.path}} dest={{user_home_base}}/{{user}}{{item.dest}} mode={{item.mode}} owner={{user}} group={{user}}
  with_items:
    - { path: '/authorized_keys', dest: '/.ssh/authorized_keys', mode: 600 }
    - { path: '/.gitconfig', dest: '/.gitconfig', mode: 644 }
  tags:
    - templates

- name: copy smb.conf
  action: copy src=../files/smb.conf dest=/etc/samba/smb.conf owner=root group=root

- name: restart samba
  command: /etc/init.d/samba restart

# do the sudoers stuff
- name: copy sudoers file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak

- name: make sure we can sudo as admin group
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^%sudoadmin' line='%sudoadmin ALL=(ALL) NOPASSWD:ALL'

- name: also make sure ssh-agent works via sudo
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'

- name: final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
