---
# This playbook will set up a vagrant box for generic LAMP development.
# See the various roles (especially roles/*/tasks/main.yml) for more details.

# Looks for the [devbox] section in the hosts file to determine which machines
# to operate on.
- hosts: t3devbox
  sudo: True

  vars_prompt:
      - name: bootstrap_webproject
        prompt: "Bootstrap webproject? Y/n"
        default: "Y"

  # Looks for roles/{role}/tasks/main.yml for tasks, roles/{role}/handlers/main.yml
  # for handlers, etcetera.
  roles:
    - common
    - user
    - nginx
    - php
    - db
    - tools
    - ansible
    - { role: bootstrap-webproject, when: bootstrap_webproject == "Y" or bootstrap_webproject == "y" }
    - cleanup

  vars_files:
    - "global_vars/devbox.yml"
